image: docker:latest
services:
- docker:dind

stages:
- build
- test
- release

before_script:
  - docker login -u ci-token -p $CI_JOB_TOKEN index.docker.io

build:
  stage: build
  script:
    - docker build -t index.docker.io/ifactorydigital/ifactoryjs_eden .
    - docker push index.docker.io/ifactorydigital/ifactoryjs_eden 
